name: Help Desk - Process Issue

on:
  issues:
    types: [opened, reopened]

jobs:
  help_desk:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Configure pnpm
        run: |
          pnpm config set "@get-subtext:registry" https://npm.pkg.github.com/
          pnpm config set "//npm.pkg.github.com/:_authToken" ${{ secrets.NPM_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Process issue
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          OPEN_SUBTITLES_API_KEY: ${{ secrets.OPEN_SUBTITLES_API_KEY }}
          SUBDL_API_KEY: ${{ secrets.SUBDL_API_KEY }}
        run: pnpm run process-issue -i ${{ github.event.issue.number }}

      - name: Pull
        run: git pull origin main

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-processed issue #${{ github.event.issue.number }} (${{ github.event.issue.title }})"
          commit_options: '--all --no-verify --allow-empty'
          file_pattern: "."
          push_options: '--force'
